package server

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"io"
	"net"
	"os"
	"os/signal"
	"syscall"

	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"

	pb "github.com/salzr/acert/proto/agentservice/v1"
)

// TODO: create a ticket in the database and share that with the agent
// With that ticket the agent will be able to init a configuration which will contain
// * client certs for mtls
// -- the client certs will be generated by the agent
// -- agent will pull in runtime the client ca's to sign the certificate
const (
	defaultGRPCPort = 50051
	defaultPort     = 8080
)

type Options struct {
	GRPCPort int
	Port     int
}

func DefaultOptions() Options {
	return Options{
		GRPCPort: defaultGRPCPort,
		Port:     defaultPort,
	}
}

type server struct {
	pb.UnimplementedAgentServiceServer

	logger *zap.Logger
}

func (s *server) Poll(stream pb.AgentService_PollServer) error {
	log := s.logger

	req, err := stream.Recv()
	if err != nil {
		return err
	}

	agentId := req.GetAgentId()
	log.Info("agent connected", zap.String("agentId", agentId))

	for {
		req, err = stream.Recv()
		if err == io.EOF {
			log.Info("agent disconnected", zap.String("agentId", agentId))
			return nil
		}
		if err != nil {
			log.Error("error receiving from agent", zap.String("agentId", agentId), zap.Error(err))
			return err
		}

		if heartbeat := req.GetHeartbeat(); heartbeat != nil {
			log.Info("agent heartbeat", zap.String("agentId", agentId))
			stream.Send(&pb.AgentResponse{
				Payload: &pb.AgentResponse_ServerStatus{
					ServerStatus: &pb.ServerStatus{
						Message: fmt.Sprintf("Acknowledged heartbeat for %s", agentId),
					},
				},
			})
		}
	}
}

func Run(ctx context.Context, options Options) error {
	log := ctx.Value("logger").(*zap.Logger)
	log = log.With(zap.String("service", "agentservice"))

	shutdown := make(chan os.Signal, 1)
	signal.Notify(shutdown, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		cert, err := tls.LoadX509KeyPair(
			"/Users/dsalazar/Documents/workspace/github.com/salzr/acert/config/certmanager/grpc.crt",
			"/Users/dsalazar/Documents/workspace/github.com/salzr/acert/config/certmanager/grpc.key")
		if err != nil {
			log.Fatal("failed to load keypair", zap.Error(err))
		}
		ca := x509.NewCertPool()
		caFilePath := "/Users/dsalazar/Documents/workspace/github.com/salzr/acert/config/certmanager/agent-ca.crt"
		caBytes, err := os.ReadFile(caFilePath)
		if err != nil {
			log.Fatal("failed to read ca cert", zap.Error(err))
		}
		if ok := ca.AppendCertsFromPEM(caBytes); !ok {
			log.Fatal("failed to parse", zap.String("filepath", caFilePath))
		}

		tlsConfig := &tls.Config{
			ClientAuth:   tls.RequireAndVerifyClientCert,
			Certificates: []tls.Certificate{cert},
			ClientCAs:    ca,
		}

		lis, err := net.Listen("tcp", fmt.Sprintf(":%d", options.GRPCPort))
		if err != nil {
			log.Fatal("failed to listen", zap.Error(err))
		}
		s := grpc.NewServer(grpc.Creds(credentials.NewTLS(tlsConfig)))
		pb.RegisterAgentServiceServer(s, &server{logger: log})
		log.Info("server listening", zap.String("address", lis.Addr().String()))
		if err := s.Serve(lis); err != nil {
			log.Fatal("failed to serve", zap.Error(err))
		}
	}()

	<-shutdown
	log.Info("shutting down")
	return nil
}
