// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.31.1
// source: agentservice.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AgentService_Poll_FullMethodName = "/v1.AgentService/Poll"
)

// AgentServiceClient is the agent API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	Poll(ctx context.Context, opts ...grpc.CallOption) (AgentService_PollClient, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Poll(ctx context.Context, opts ...grpc.CallOption) (AgentService_PollClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Poll_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServicePollClient{stream}
	return x, nil
}

type AgentService_PollClient interface {
	Send(*AgentRequest) error
	Recv() (*AgentResponse, error)
	grpc.ClientStream
}

type agentServicePollClient struct {
	grpc.ClientStream
}

func (x *agentServicePollClient) Send(m *AgentRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServicePollClient) Recv() (*AgentResponse, error) {
	m := new(AgentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	Poll(AgentService_PollServer) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) Poll(AgentService_PollServer) error {
	return status.Errorf(codes.Unimplemented, "method Poll not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Poll_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Poll(&agentServicePollServer{stream})
}

type AgentService_PollServer interface {
	Send(*AgentResponse) error
	Recv() (*AgentRequest, error)
	grpc.ServerStream
}

type agentServicePollServer struct {
	grpc.ServerStream
}

func (x *agentServicePollServer) Send(m *AgentResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServicePollServer) Recv() (*AgentRequest, error) {
	m := new(AgentRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Poll",
			Handler:       _AgentService_Poll_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agentservice.proto",
}
