// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: agentservice.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentRequest_Heartbeat
	Payload       isAgentRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_agentservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_agentservice_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRequest) GetPayload() isAgentRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentRequest) GetHeartbeat() *AgentHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentRequest_Payload interface {
	isAgentRequest_Payload()
}

type AgentRequest_Heartbeat struct {
	Heartbeat *AgentHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentRequest_Heartbeat) isAgentRequest_Payload() {}

type AgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentResponse_ServerTask
	//	*AgentResponse_ServerStatus
	Payload       isAgentResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_agentservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_agentservice_proto_rawDescGZIP(), []int{1}
}

func (x *AgentResponse) GetPayload() isAgentResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentResponse) GetServerTask() *ServerTask {
	if x != nil {
		if x, ok := x.Payload.(*AgentResponse_ServerTask); ok {
			return x.ServerTask
		}
	}
	return nil
}

func (x *AgentResponse) GetServerStatus() *ServerStatus {
	if x != nil {
		if x, ok := x.Payload.(*AgentResponse_ServerStatus); ok {
			return x.ServerStatus
		}
	}
	return nil
}

type isAgentResponse_Payload interface {
	isAgentResponse_Payload()
}

type AgentResponse_ServerTask struct {
	ServerTask *ServerTask `protobuf:"bytes,1,opt,name=server_task,json=serverTask,proto3,oneof"`
}

type AgentResponse_ServerStatus struct {
	ServerStatus *ServerStatus `protobuf:"bytes,2,opt,name=server_status,json=serverStatus,proto3,oneof"`
}

func (*AgentResponse_ServerTask) isAgentResponse_Payload() {}

func (*AgentResponse_ServerStatus) isAgentResponse_Payload() {}

type AgentHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_agentservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agentservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_agentservice_proto_rawDescGZIP(), []int{2}
}

func (x *AgentHeartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ServerTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerTask) Reset() {
	*x = ServerTask{}
	mi := &file_agentservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTask) ProtoMessage() {}

func (x *ServerTask) ProtoReflect() protoreflect.Message {
	mi := &file_agentservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTask.ProtoReflect.Descriptor instead.
func (*ServerTask) Descriptor() ([]byte, []int) {
	return file_agentservice_proto_rawDescGZIP(), []int{3}
}

func (x *ServerTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ServerTask) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_agentservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agentservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_agentservice_proto_rawDescGZIP(), []int{4}
}

func (x *ServerStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agentservice_proto protoreflect.FileDescriptor

const file_agentservice_proto_rawDesc = "" +
	"\n" +
	"\x12agentservice.proto\x12\x02v1\"h\n" +
	"\fAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x122\n" +
	"\theartbeat\x18\x02 \x01(\v2\x12.v1.AgentHeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x86\x01\n" +
	"\rAgentResponse\x121\n" +
	"\vserver_task\x18\x01 \x01(\v2\x0e.v1.ServerTaskH\x00R\n" +
	"serverTask\x127\n" +
	"\rserver_status\x18\x02 \x01(\v2\x10.v1.ServerStatusH\x00R\fserverStatusB\t\n" +
	"\apayload\".\n" +
	"\x0eAgentHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"?\n" +
	"\n" +
	"ServerTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"(\n" +
	"\fServerStatus\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2?\n" +
	"\fAgentService\x12/\n" +
	"\x04Poll\x12\x10.v1.AgentRequest\x1a\x11.v1.AgentResponse(\x010\x01B(Z&github.com/salzr/proto/agentservice/v1b\x06proto3"

var (
	file_agentservice_proto_rawDescOnce sync.Once
	file_agentservice_proto_rawDescData []byte
)

func file_agentservice_proto_rawDescGZIP() []byte {
	file_agentservice_proto_rawDescOnce.Do(func() {
		file_agentservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentservice_proto_rawDesc), len(file_agentservice_proto_rawDesc)))
	})
	return file_agentservice_proto_rawDescData
}

var file_agentservice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agentservice_proto_goTypes = []any{
	(*AgentRequest)(nil),   // 0: v1.AgentRequest
	(*AgentResponse)(nil),  // 1: v1.AgentResponse
	(*AgentHeartbeat)(nil), // 2: v1.AgentHeartbeat
	(*ServerTask)(nil),     // 3: v1.ServerTask
	(*ServerStatus)(nil),   // 4: v1.ServerStatus
}
var file_agentservice_proto_depIdxs = []int32{
	2, // 0: v1.AgentRequest.heartbeat:type_name -> v1.AgentHeartbeat
	3, // 1: v1.AgentResponse.server_task:type_name -> v1.ServerTask
	4, // 2: v1.AgentResponse.server_status:type_name -> v1.ServerStatus
	0, // 3: v1.AgentService.Poll:input_type -> v1.AgentRequest
	1, // 4: v1.AgentService.Poll:output_type -> v1.AgentResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agentservice_proto_init() }
func file_agentservice_proto_init() {
	if File_agentservice_proto != nil {
		return
	}
	file_agentservice_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentRequest_Heartbeat)(nil),
	}
	file_agentservice_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentResponse_ServerTask)(nil),
		(*AgentResponse_ServerStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentservice_proto_rawDesc), len(file_agentservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentservice_proto_goTypes,
		DependencyIndexes: file_agentservice_proto_depIdxs,
		MessageInfos:      file_agentservice_proto_msgTypes,
	}.Build()
	File_agentservice_proto = out.File
	file_agentservice_proto_goTypes = nil
	file_agentservice_proto_depIdxs = nil
}
